name: Build & Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip setuptools wheel

      - run: npm install
      - run: npm test
