name: Build & Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: Setup Python and Install distutils
        id: py
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip3 install distutils setuptools
        env:
          PYTHON: '${{ steps.py.outputs.python-path }}'
      - run: npm install
        env:
          NODE_GYP_FORCE_PYTHON: '${{ steps.py.outputs.python-path }}'
      - run: npm test
        env:
          NODE_GYP_FORCE_PYTHON: '${{ steps.py.outputs.python-path }}'
